### ISSUE TITLE
-core fails to build with PIE, i386, GCC < 4.7

### ISSUE THREAD

**Issue by GoogleCodeExporter** [EmulatorArchive/mupen64plus#591]
```
OpenBSD recently switched to PIE on i386. The combination of PIE, i386, and GCC 
4.2.1 is probably rare enough that this hasn’t been seen before:

https://github.com/mupen64plus/mupen64plus-core/blob/master/src/r4300/x86/rjump.
c#L104

cc -O2 -pipe -g -DIOAPI_NO_64  -Wall -ffast-math -fno-strict-aliasing 
-fvisibility=hidden -I../../src -DM64P_PARALLEL -fno-PIC -I/usr/include 
-I/usr/local/include/libpng16 -I/usr/local/include -I/usr/local/include/SDL 
-D_GNU_SOURCE=1 -D_REENTRANT -I/usr/X11R6/include -DXTHREADS -DM64P_OSD 
-I/usr/X11R6/include/freetype2 -I/usr/X11R6/include -I/usr/X11R6/include 
-I/usr/include/dev/pci/drm -I/usr/X11R6/include -I/usr/include/dev/pci/drm 
-DDYNAREC -DNOCRYPT -DNOUNCRYPT -MD   -c -o _obj/r4300/x86/rjump.o 
../../src/r4300/x86/rjump.c
../../src/r4300/x86/rjump.c:104:23: error: missing binary operator before token 
"("
Makefile:581: recipe for target '_obj/r4300/x86/rjump.o' failed
```

Original issue reported on code.google.com by `anth...@cathet.us` on 9 Jan 2014 at 4:39
